// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Confetti: typeof import('./components/Confetti.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    GameArea: typeof import('./components/GameArea.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MyButton: typeof import('./components/MyButton.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    NumberCard: typeof import('./components/NumberCard.vue')['default']
    SelectButton: typeof import('./components/SelectButton.vue')['default']
    SelectCard: typeof import('./components/SelectCard.vue')['default']
  }
}
